nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxfixes",
  "libxrandr",
  "mesa",
  "pango",
  "cairo",
  "gtk3",
  "libgbm",
  "stdenv.cc.cc.lib" # Критически важный пакет для C++ либ
]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[variables]
LD_LIBRARY_PATH = "/nix/var/nix/profiles/default/lib"
