[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxfixes",
  "libxrandr",
  "mesa",
  "pango",
  "cairo",
  "gtk3",
  "libgbm"
]

# Добавь вот эту часть:
[variables]
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:/nix/var/nix/profiles/default/lib"
